export enum ApiUrl {
  getViewList = '/view/list', // 获取视图
  getObjectList = '/navigation/get_object_list', //获取列表
  getAllInVolumeRecordList = '/navigation/get_all_record_list', //获取卷内件视图
  getBreadCrumbsById = '/navigation/get_bread_crumbs_by_id',
  findCateIdByPlanId = '/category/get_category_by_file_plan_id',
  getFormColumnConfigByMetadataSchemeId = '/metadata/get_form_column_config_by_metadata_scheme_id',
  getStandardCodeByName = '/metadata/get_standard_code_by_name',
  getRootCategoryInfo = '/category/get_category_detail',
  viewArchiveList = '/view/view_archive_list', // 获取档案视图表格数据
  putInRecycle = '/file_plan/put_in_recycle', //放入回收站
  putVolumeInRecycle = '/volume/put_in_recycle',
  putRecordInRecycle = '/record/put_in_recycle',
  downloadArchive = '/archive/download_archive', //档案元数据下载
  getYearListsByCategoryId = '/file_plan/get_year_list_by_id', //根据门类id获取年度计划列表
  generateArchivesCode = '/archive/generate_archives_code', // 生成档号
  setYear = '/archive/update_year', //更新计划
  findArchivesByWrapper = '/archive/find_archives_by_wrapper',
  getDataByView = '/view/get_data_by_view',
  getAttributeList = '/metadata/get_attribute_list_by_type_name_or_metadata_id',
  markArchive = '/archive/mark_archive', //手动打标
  labelExtraction = '/record/label_extraction', //标签提取
  startConvertFormat = '/convert_format/start_convert_format', //格式转化
  archiveDocumentDigitization = '/archive/archive_document_digitization',
  validator = '/archive/validate', //四性检测
  archivesValidateCheck = '/archive/archives_validate_check', // 归档前置校验
  isExistencePhysicalArchive = '/archive/existence_physical_archive',
  getBindWarehouseByCategoryId = '/category/get_bind_warehouse', // 根据门类ID获取门类下的绑定库房
  archiveVolume = '/volume/archive_volume',
  archiveRecord = '/record/archive_record',
  getMarkDetails = '/mark_error/get_details', // 获取标错信息
  createOrUpdateMarkErrorRecord = '/mark_error/create_or_update_mark_error_record', // 确认标错
  backUps = '/backup/start', // 确认备份
  addAppraisalLibrary = '/archive/add_appraisal_library', // 档案鉴定
  getSourceFolderNonexistentIdList = '/archive/get_source_folder_nonexistent_id_list',
  getFilePlanList = '/file_plan/get_list',
  syncLibraryRearrange = '/archive/sync_library_rearrange',
  rearrange = '/archive/rearrange',
  modifyRearrangeSourcePath = '/archive/modify_rearrange_source_path',
  getColumnByMetadataId = '/metadata/get_form_column_config_by_metadata_scheme_id',
  getSystemCollectionList = '/navigation/get_system_collection_list', // 业务系统收集列表数据获取
  getCategoryDetail = '/category/get_category_detail', //获取分类信息
  updateClassification = '/archive/update_classification', //指定分类
  archiveRecordRearrange = '/archive/record_rearrange', // 卷内重新整理
  archiveTransferExport = '/archive/archive_transfer_export', // 移交导出
  archiveEarlyHandover = '/archive/archive_early_handover', // 提前移交
  linkArchiveToTarget = '/archive/link_archive_to_target', // 入档案编研、入专题库
  syncDataToSyncLibrary = '/archive/sync_data_to_sync_library',
  getShareUnitList = '/archive_share/get_share_unit_list', //获取共享单位
  launchShare = '/archive_share/launch_share', //发起共享
  getVolumeListByParentId = '/volume/get_volume_info', // 查询案卷信息
  moveInVolume = '/volume/move_in_volume', // 移动到卷内
  exportHouseDocument = '/archive/export_archives_by_key',
  getClassTreeNodeList = '/navigation/get_class_tree_node_list',
  getTreeNodes = '/navigation/get_tree_node_list_by_parent_id',
  getPrintModuleListByMetadataId = '/metadata/get_report_template_type_list_by_archive_id',
  checkBeforePrint = '/archive/check_report_template',
  printData = '/archive/export_report',
  getPrintData = '/archives/get_report_data',
  getSelectAllList = '/archive/get_select_all_list',
  printVolumeData = '/archive/volume_export_report',
  getBaseInfoByMetadataId = '/metadata/get_form_base_info_by_metadata_scheme_id',
  checkExcelRequiredValue = '/metadata/get_required_value',
  getDocMatchField = '/doc_match/get_list',
  getMappingRuleListByMetadataIdAndFondsId = '/attribute_mapping_scheme/get_attribute_mapping_scheme_list',
  updateArchivesAttribute = '/archive/update_archives_attribute', //批量修改
  getSheetInfoByPath = '/archive/get_sheet_name_and_head',
  deleteMappingRule = '/attribute_mapping_scheme/delete_attribute_mapping_scheme', // 删除映射规则
  saveMappingRule = '/attribute_mapping_scheme/create_attribute_mapping_scheme', // 新建映射规则
  updateMappingRule = '/attribute_mapping_scheme/update_attribute_mapping_scheme', // 修改映射规则
  downloadImportTemplate = '/archive/download_archive_import_template', // 下载导入模板
  moveRecordInVolume = '/record/move_record', //移动卷内件
  createVolume = '/volume/create_volume',
  importDataSingle = '/record/hook_documents',
  importData = '/archive/import_data', // 数据导入
  getConvertFormatResult = '/convert_format/get_convert_format_result', //获取格式转换记录
  /**快速著录 */
  villageCreateRecord = '/record/fast_description_record',
  villageCreateVolume = '/volume/fast_description_volume',
  getCategoryCodeById = '/category/get_category_list_by_id',
  getImportInfo = '/archive/import_live',
  updateRecordForm = '/record/update_record',
  createRecord = '/record/create_record',

  /** 修订库 */
  getVerifyRecordsBatch = '/validator_batch/get_validator_batch_list',
  delRecordbatch = '/validator_batch/delete_validator_batch',
  getVerifyReviseBatch = '/revise_batch/get_revise_batch_list',
  delRevise = '/revise_batch/delete_revise_batch',

  /** 专题库 */
  getClassifyList = '/subject_classify/get_classify_list',
  getSubjectList = '/subject/get_subject_list',
  getSubjectArchiveList = '/subject/get_subject_archive_list',
  getSubjectLinkedArchive = '/subject/get_subject_linked_archive',
  getCompilingCarList = '/compiling_car/get_compiling_car_list',
  oneClickSync = '/subject/one_click_sync',
  archiveUnlink = '/archive/archive_unlink',
  addEditingStore = '/compiling_car/add_compiling_car',
  getArchivesFromEditingStore = '/compiling_car/get_compiling_car_list',
  removeArchivesFromEditingStore = '/compiling_car/delete_compiling_car_archives',
  exportData = '/subject_classify/subject_task_archives_export', //专题库导出数据
  archivesExport = '/subject_classify/archives_export', //专题库导出报表
  getSubjectRule = '/subject/join_rule/get_subject_rule',
  deleteClassify = '/subject_classify/delete_classify',
  deleteSubject = '/subject/delete_subject',
  updateClassify = '/subject_classify/update_classify',
  createTaskClassification = '/subject_classify/create_task_classification',
  createClassify = '/subject_classify/create_classify',
  subjectDetail = '/subject/detail',
  updateSubject = '/subject/update_subject',
  createSubject = '/subject/create_subject',
  createRule = '/subject/join_rule/create_rule',
  updateRule = '/subject/join_rule/update_rule',
  deleteRule = '/subject/join_rule/delete_rule',
  getRecordPolicyDetail = '/metadata/get_record_policy_detail',
  /** 编研库 */
  subjectArchivesExport = '/subject_classify/subject_archives_export',
  getCompilingFormDetails = '/compiling/get_compiling_form_details',
  execAutoJoin = '/subject/join_rule/exec_auto_join',
}
